# Enable C++ support
language: cpp

os: 
  - linux
#  - osx
#  - windows

# Compiler selection
compiler:
  - g++

# Build steps
script:
  - cd cmake_build
  - cmake ..
  - make 
  - cp biorobots ..
  - cd ..
  - biorobots 

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
