os:
  - linux
#  - osx

language: cpp

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update ;
      brew install g++
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CC=gcc-7 ;
      export CXX=g++-7 ;
    fi

# Build steps
script:
  - cd cmake_build
  - cmake ..
  - make 
  - cp biorobots ..
  - cd ..
  - biorobots 

notifications:
  email:
    recipients:
      - randy.heiland@gmail.com
    on_success: always # default: change  (always, never)
    on_failure: always # default: always
